// mobile/app/components/login/LoginForm.tsx
import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, Alert, StyleSheet } from 'react-native';
import axios from 'axios';
import { NativeStackScreenProps } from '@react-navigation/native-stack';

type RootStackParamList = {
  Login: undefined;
  PinValidation: { email: string };
};

type LoginProps = NativeStackScreenProps<RootStackParamList, 'Login'>;

const Login: React.FC<LoginProps> = ({ navigation }) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const isLoginFormValid = email.includes('@') && password.length > 0;

  const handleLogin = async () => {
    if (!isLoginFormValid) return;
    try {
      const response = await axios.post('http://localhost:80/api/utilisateur/login', {
        Email: email,
        Password: password,
      });
      if (response.status === 200) {
        Alert.alert('Succès', 'Connexion réussie.');
        navigation.navigate('PinValidation', { email });
      } else {
        Alert.alert('Erreur', 'Email ou mot de passe incorrect.');
      }
    } catch (error) {
      Alert.alert('Erreur', 'Problème de connexion.');
    }
  };

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Login</Text>
      <TextInput
        style={styles.input}
        placeholder="Entrez votre email"
        keyboardType="email-address"
        autoCapitalize="none"
        value={email}
        onChangeText={setEmail}
      />
      <TextInput
        style={styles.input}
        placeholder="Entrez votre mot de passe"
        secureTextEntry
        value={password}
        onChangeText={setPassword}
      />
      <TouchableOpacity 
        style={[styles.button, !isLoginFormValid && styles.buttonDisabled]} 
        onPress={handleLogin} 
        disabled={!isLoginFormValid}
      >
        <Text style={styles.buttonText}>Continuer avec l'idP</Text>
      </TouchableOpacity>
    </View>
  );
};

const PinValidation: React.FC<{ route: { params: { email: string } }; navigation: any }> = ({ route, navigation }) => {
  const { email } = route.params;
  const [pin, setPin] = useState('');
  const isPinFormValid = pin.length === 6;

  const handlePinSubmit = async () => {
    if (!isPinFormValid) return;
    try {
      const response = await axios.post('http://localhost:80/api/utilisateur/ValiderPin', {
        Pin: pin,
        Email: email,
      });
      if (response.status === 200) {
        Alert.alert('Succès', 'PIN validé.');
        navigation.navigate('Login');
      } else {
        Alert.alert('Erreur', 'PIN incorrect.');
      }
    } catch (error) {
      Alert.alert('Erreur', 'Problème de connexion.');
    }
  };

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Validation du PIN</Text>
      <TextInput
        style={styles.input}
        placeholder="Entrez votre PIN"
        keyboardType="numeric"
        maxLength={6}
        value={pin}
        onChangeText={setPin}
      />
      <TouchableOpacity 
        style={[styles.button, !isPinFormValid && styles.buttonDisabled]} 
        onPress={handlePinSubmit} 
        disabled={!isPinFormValid}
      >
        <Text style={styles.buttonText}>Valider</Text>
      </TouchableOpacity>
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#f3f4f6' },
  title: { fontSize: 24, fontWeight: 'bold', color: '#1e3a8a', marginBottom: 20 },
  input: { width: '80%', padding: 10, borderWidth: 1, borderColor: '#ccc', borderRadius: 8, backgroundColor: '#fff', marginBottom: 10 },
  button: { width: '80%', padding: 15, backgroundColor: '#1e3a8a', borderRadius: 8, alignItems: 'center' },
  buttonDisabled: { backgroundColor: '#ccc' },
  buttonText: { color: '#fff', fontWeight: 'bold' },
});

export { Login, PinValidation };

// front-crypto/src/components/Login/LoginForm.vue
<template>
  <div class="h-screen flex items-center justify-center">
    <!-- Formulaire Login -->
    <form v-if="!isPinFormVisible" @submit.prevent="handleLogin" class="bg-gray-100 p-8 rounded-lg shadow-md w-96">
      <h1 class="text-2xl text-center text-blue-900 mb-6">Login</h1>

      <!-- Email Field -->
      <div class="mb-4">
        <input
          type="email"
          id="email"
          v-model="email"
          required
          placeholder="Entrez votre email"
          class="w-full p-3 border border-gray-300 rounded-md text-gray-800"
        />
      </div>
      <div class="mb-6">
        <input
          type="password"
          id="password"
          v-model="password"
          required
          placeholder="Entrez votre mot de passe"
          class="w-full p-3 border border-gray-300 rounded-md text-gray-800"
        />
      </div>
      <button
        type="submit"
        :disabled="!isLoginFormValid"
        class="w-full py-3 bg-blue-900 text-white rounded-md font-semibold disabled:bg-gray-400 hover:bg-blue-700 focus:outline-none"
      >
        Login
      </button>

      <!-- Links -->
      <div class="flex justify-between mt-4">
        <a href="#" class="text-blue-900 hover:underline">Mot de passe oublié?</a>
        <a href="#" class="text-blue-900 hover:underline">Créer un compte</a>
      </div>
    </form>

    <!-- Formulaire PIN -->
    <form v-if="isPinFormVisible" @submit.prevent="handlePinSubmit" class="bg-gray-100 p-8 rounded-lg shadow-md w-96">
      <h1 class="text-2xl text-center text-blue-900 mb-6">Validation du PIN</h1>

      <!-- PIN Field -->
      <div class="mb-4">
        <input
          type="password"
          id="pin"
          v-model="pin"
          required
          placeholder="Entrez votre PIN"
          maxlength="6"
          class="w-full p-3 border border-gray-300 rounded-md text-gray-800"
        />
      </div>
      <button
        type="submit"
        :disabled="!isPinFormValid"
        class="w-full py-3 bg-blue-900 text-white rounded-md font-semibold disabled:bg-gray-400 hover:bg-blue-700 focus:outline-none"
      >
        Valider
      </button>
    </form>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';
import { useRouter } from 'vue-router';
import axios from 'axios';

const router = useRouter();
const email = ref('');
const password = ref('');
const pin = ref('');
const isPinFormVisible = ref(false); // Contrôle l'affichage du formulaire PIN
const isLoginFormValid = computed(() => {
  return email.value.includes('@') && password.value.length > 0;
});
const isPinFormValid = computed(() => pin.value.length === 5);

// Handle Login
const handleLogin = async () => {
  if (isLoginFormValid.value) {
    try {
      const response = await axios.post('http://localhost:5092/api/utilisateur/login', {
        Email: email.value,
        Password: password.value,
      });

      if (response.status === 200) {
        console.log('Login success:', response.data);
        // Transition vers la validation du PIN après une connexion réussie
        isPinFormVisible.value = true;
      } else {
        console.error('Erreur de login:', response.data);
      }
    } catch (error) {
      console.error('Erreur lors de la connexion:', error);
    }
  }
};

// Handle PIN submission
const handlePinSubmit = async () => {
  if (isPinFormValid.value) {
    try {
      const response = await axios.post('http://localhost:5092/api/utilisateur/ValiderPin', {
        Pin: pin.value,
        Email: email.value,
      });

      if (response.status === 200) {
        console.log('PIN validé:', response.data);
        await router.push('/home/listeCrypto');
      } else {
        console.error('Erreur de validation du PIN:', response.data);
      }
    } catch (error) {
      console.error('Erreur lors de la validation du PIN:', error);
    }
  }
};
</script>

<style scoped>
/* Utilisation du même style pour les deux formulaires */
</style>
